# Generated by Django 5.2 on 2025-04-09 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(blank=True, null=True, verbose_name='Текст сообщения')),
                ('file', models.FileField(blank=True, null=True, upload_to='media/', verbose_name='Медиафайл')),
                ('media_type', models.CharField(blank=True, choices=[('image', 'Изображение'), ('video', 'Видео')], max_length=10, null=True, verbose_name='Тип медиафайла')),
            ],
            options={
                'verbose_name': 'Вопрос-ответ',
                'verbose_name_plural': 'Вопросы-ответы',
            },
        ),
    ]
