# Generated by Django 5.2 on 2025-04-12 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faq', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='faq',
            name='text',
        ),
        migrations.AddField(
            model_name='faq',
            name='answer',
            field=models.TextField(blank=True, null=True, verbose_name='Ответ'),
        ),
        migrations.AddField(
            model_name='faq',
            name='question',
            field=models.TextField(blank=True, null=True, verbose_name='Вопрос'),
        ),
    ]
