# Generated by Django 5.2 on 2025-04-12 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_api_key_user_api_secret'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='loss',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='pair',
            field=models.CharField(blank=True, choices=[('KAS_USDT', 'KAS/USDT'), ('BTC_USDC', 'BTC/USDC')], max_length=30, null=True, verbose_name='Торговая пара'),
        ),
        migrations.AddField(
            model_name='user',
            name='pause',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='profit',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
