# Generated by Django 5.2 on 2025-04-13 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_user_is_active_user_loss_user_pair_user_pause_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='buy_amount',
            field=models.DecimalField(decimal_places=2, default=10.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='user',
            name='pair',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Торговая пара'),
        ),
    ]
