# Generated by Django 5.2 on 2025-04-14 07:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_rename_price_deal_buy_price_remove_deal_side_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='is_active',
            new_name='autobuy',
        ),
    ]
