# Generated by Django 5.2 on 2025-04-14 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_rename_is_active_user_autobuy'),
    ]

    operations = [
        migrations.AddField(
            model_name='deal',
            name='is_autobuy',
            field=models.BooleanField(default=False),
        ),
    ]
