# Generated by Django 5.2 on 2025-04-17 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_deal_is_autobuy'),
    ]

    operations = [
        migrations.AddField(
            model_name='deal',
            name='user_order_number',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
