# Generated by Django 5.2 on 2025-04-15 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('editing', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BotMessageForSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
            ],
            options={
                'verbose_name': 'Сообщение пользователю для оформления подписки',
                'verbose_name_plural': 'Сообщение пользователю для оформления подписки',
            },
        ),
        migrations.AlterModelOptions(
            name='botmessageforstart',
            options={'verbose_name': 'Сообщение пользователю по команде start', 'verbose_name_plural': 'Сообщение пользователю по команде start'},
        ),
        migrations.AlterModelOptions(
            name='botmessagesforkeys',
            options={'verbose_name': 'Сообщение пользователю по команде set_keys', 'verbose_name_plural': 'Сообщение пользователю по команде set_keys'},
        ),
    ]
