# Generated by Django 5.2 on 2025-04-16 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('editing', '0002_botmessageforsubscription_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='botmessageforstart',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='bot_messages/'),
        ),
        migrations.AddField(
            model_name='botmessageforsubscription',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='bot_messages/'),
        ),
        migrations.AddField(
            model_name='botmessagesforkeys',
            name='access_image',
            field=models.FileField(blank=True, null=True, upload_to='bot_messages/'),
        ),
        migrations.AddField(
            model_name='botmessagesforkeys',
            name='secret_image',
            field=models.FileField(blank=True, null=True, upload_to='bot_messages/'),
        ),
    ]
