# Generated by Django 5.2 on 2025-04-17 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('editing', '0003_botmessageforstart_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='botmessageforstart',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='media/'),
        ),
        migrations.AlterField(
            model_name='botmessageforsubscription',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='media/'),
        ),
        migrations.AlterField(
            model_name='botmessagesforkeys',
            name='access_image',
            field=models.FileField(blank=True, null=True, upload_to='media/'),
        ),
        migrations.AlterField(
            model_name='botmessagesforkeys',
            name='secret_image',
            field=models.FileField(blank=True, null=True, upload_to='media/'),
        ),
    ]
