# Generated by Django 5.2 on 2025-04-14 13:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0002_botmessageforsubscription_alter_subscription_options'),
        ('users', '0009_deal_is_autobuy'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscription',
            name='name',
        ),
        migrations.RemoveField(
            model_name='subscription',
            name='telegram_id',
        ),
        migrations.AddField(
            model_name='subscription',
            name='user',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='subscription', to='users.user', verbose_name='Пользователь'),
            preserve_default=False,
        ),
    ]
