# Generated by Django 5.2 on 2025-04-15 10:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0003_remove_subscription_name_and_more'),
        ('users', '0009_deal_is_autobuy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subscription', to='users.user', verbose_name='Пользователь'),
        ),
    ]
