# Generated by Django 5.2 on 2025-04-15 10:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0004_alter_subscription_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BotMessageForSubscription',
        ),
    ]
